import type { NextRequest } from "next/server";
import { ok, bad, notFound, readJson } from "@/lib/server/http";
import { getIdentity, scopeOf } from "@/lib/server/identity";
import { store, newId } from "@/lib/server/store";
import { explain, selfCritique } from "@/lib/core";
import { chat, type ProviderConfig } from "@/lib/providers";
import type { Report } from "@/lib/models";

export const dynamic = "force-dynamic";

// POST /api/reports/generate { hypothesisId, evidenceId?, provider? }
// The report body is built DETERMINISTICALLY from the engine. If a provider config is supplied
// and reachable, an AI executive summary is appended and clearly labelled. The verdict in the
// report is ALWAYS the engine's — the LLM cannot change it.
export async function POST(req: NextRequest) {
  const ident = getIdentity(req);
  const body = await readJson<{ hypothesisId?: string; evidenceId?: string; provider?: ProviderConfig }>(req);
  if (!body?.hypothesisId) return bad("hypothesisId is required");
  const h = store.getHypothesis(ident, body.hypothesisId);
  if (!h) return notFound("hypothesis");

  const evs = store.listEvidence(ident, h.id);
  if (!evs.length) return bad("no evidence to report on");
  const rec = body.evidenceId ? store.getEvidence(ident, body.evidenceId) : evs[0];
  if (!rec) return notFound("evidence");

  const ex = explain(rec.evidence, h.title);
  const crit = selfCritique(rec.evidence);
  let markdown = deterministicReport(h.title, ex, crit);
  let aiAssisted = false;

  if (body.provider?.providerId && body.provider?.model) {
    try {
      const summary = await chat(body.provider, [
        { role: "system", content: "You write a 3-sentence neutral executive summary of a research verdict. You MUST NOT change the verdict or invent evidence. State the verdict, the key reason, and the main open question." },
        { role: "user", content: `Verdict: ${crit.finalVerdict}. Support ${ex.support}, calibration ${crit.calibration.score}/100. For: ${ex.supporting.join("; ")}. Against: ${ex.against.join("; ")}. Missing: ${ex.missing.join("; ")}.` },
      ]);
      if (summary.trim()) {
        markdown += `\n\n## Executive summary (AI-assisted)\n> Generated by ${body.provider.providerId}/${body.provider.model}. The verdict above is the engine's and was not altered.\n\n${summary.trim()}\n`;
        aiAssisted = true;
      }
    } catch (e: any) {
      markdown += `\n\n> AI summary unavailable (${e?.message || "provider error"}). Deterministic report stands.\n`;
    }
  }

  const verdicts = store.listVerdicts(ident, h.id);
  const report: Report = {
    id: newId("rep"), ...scopeOf(ident), hypothesisId: h.id,
    verdictId: verdicts[0]?.id || "",
    title: `Report — ${h.title}`, markdown, aiAssisted,
    createdAt: new Date().toISOString(),
  };
  store.createReport(report);
  return ok({ report }, 201);
}

function deterministicReport(title: string, ex: any, crit: any): string {
  const li = (xs: string[]) => xs.map((x) => `- ${x}`).join("\n");
  return [
    `# ${title}`,
    ``,
    `**Verdict (engine): ${crit.finalVerdict}**${crit.downgrade ? ` — ${crit.downgrade}` : ""}`,
    `Support ${ex.support} · Calibration ${crit.calibration.score}/100 (${crit.calibration.band})`,
    ``,
    `## Evidence for`, li(ex.supporting),
    ``, `## Evidence against`, li(ex.against),
    ``, `## Missing evidence`, li(ex.missing),
    ``, `## Why alternatives were rejected`,
    li(ex.rejectedAlternatives.map((a: any) => `not ${a.verdict}: ${a.why}`)),
    ``, `## Self-critique (${crit.survived}/${crit.attacks.length} attacks survived)`,
    li(crit.attacks.map((a: any) => `[${a.survives ? "held" : "LANDED"}] (${a.target}) ${a.attack}`)),
    ``, `## Confidence`, ex.confidenceExplanation,
    ``, `_Report body generated deterministically by the HypothesisOS engine._`,
  ].join("\n");
}
