"use client";
import { useState, useEffect } from "react";
import Link from "next/link";
import { api } from "@/lib/client";
import { Mark } from "@/components/logo/Mark";

type DecisionBrief = {
  id: string; title: string; verdict: string | null;
  support: number; debt: number; risk: string; riskScore: number;
  effort: string; daysOpen: number;
};

type Action = { type: string; decision: string; action: string };

type BriefData = {
  generatedAt: string;
  summary: {
    total: number; go: number; kill: number; unresolved: number;
    avgDebt: number; avgSupport: number; healthScore: number;
    criticalRisks: number; pendingApprovals: number; totalReports: number;
  };
  topRisks: DecisionBrief[];
  nearGo: DecisionBrief[];
  criticalKill: DecisionBrief[];
  stalled: DecisionBrief[];
  priorityActions: Action[];
};

const VERDICT_CLS: Record<string, string> = {
  GO: "text-go", KILL: "text-kill", UNRESOLVED: "text-unresolved",
};
const RISK_CLS: Record<string, string> = {
  LOW: "text-go", MEDIUM: "text-unresolved", HIGH: "text-kill", CRITICAL: "text-kill",
};
const ACTION_TYPE_ICON: Record<string, string> = {
  risk: "⚑", opportunity: "◈", stalled: "⏱",
};

function downloadMD(brief: BriefData) {
  const date = new Date(brief.generatedAt).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const md = [
    `# Board Intelligence Brief`,
    `**Generated:** ${date}`,
    ``,
    `## Portfolio Summary`,
    `- Total Decisions: ${brief.summary.total}`,
    `- GO: ${brief.summary.go} | KILL: ${brief.summary.kill} | UNRESOLVED: ${brief.summary.unresolved}`,
    `- Portfolio Health Score: ${brief.summary.healthScore}/100`,
    `- Avg Evidence Debt: ${brief.summary.avgDebt}%`,
    `- Avg Support: ${brief.summary.avgSupport}%`,
    `- Critical Risks: ${brief.summary.criticalRisks}`,
    ``,
    `## Priority Actions`,
    ...brief.priorityActions.map((a) => `- [${a.type.toUpperCase()}] ${a.action}`),
    ``,
    `## Top Risks`,
    ...brief.topRisks.map((d) => `- ${d.title} (${d.verdict} | ${d.risk} risk | ${(d.support*100).toFixed(0)}% support)`),
    ``,
    `## Near-GO Decisions`,
    ...brief.nearGo.map((d) => `- ${d.title} (${(d.support*100).toFixed(0)}% support | ${d.debt.toFixed(0)}% debt)`),
    ``,
    `## Stalled Decisions`,
    ...brief.stalled.map((d) => `- ${d.title} (${d.daysOpen} days open)`),
    ``,
    `---`,
    `*Generated by HypothesisOS — Deterministic Decision Intelligence Platform*`,
  ].join("\n");

  const blob = new Blob([md], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a"); a.href = url; a.download = "board-brief.md"; a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function downloadJSON(brief: BriefData) {
  const blob = new Blob([JSON.stringify(brief, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a"); a.href = url; a.download = "board-brief.json"; a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export default function BoardBrief() {
  const [data, setData] = useState<BriefData | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api<BriefData>("/api/board-brief")
      .catch(() => null)
      .then((r) => { if (r) setData(r); })
      .finally(() => setLoading(false));
  }, []);

  const healthBand = (s: number) => s >= 70 ? { label: "Healthy", cls: "text-go" } : s >= 45 ? { label: "Developing", cls: "text-unresolved" } : { label: "At Risk", cls: "text-kill" };

  if (loading) return <div className="card animate-pulse h-64 bg-white/3" />;

  if (!data) return (
    <div className="card text-center py-8 space-y-2">
      <p className="text-sm text-steel">No data available.</p>
      <Link href="/workflow" className="btn-primary text-sm inline-flex">Run first decision →</Link>
    </div>
  );

  const hb = healthBand(data.summary.healthScore);
  const date = new Date(data.generatedAt).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  return (
    <div className="mx-auto max-w-3xl space-y-0 print-brief">
      {/* Controls — print hidden */}
      <div className="mb-5 flex flex-wrap items-center justify-between gap-2 print:hidden">
        <div className="label">Board Intelligence Brief</div>
        <div className="flex gap-2">
          <button onClick={() => downloadMD(data)} className="btn-ghost text-sm">↓ Markdown</button>
          <button onClick={() => downloadJSON(data)} className="btn-ghost text-sm">↓ JSON</button>
          <button onClick={() => window.print()} className="btn-primary text-sm">Print / PDF</button>
        </div>
      </div>

      {/* Cover */}
      <div className="card mb-4 print:min-h-[40vh] print:flex print:flex-col print:justify-between">
        <div>
          <div className="flex items-center gap-3 mb-6">
            <Mark size={32} variant="mono" />
            <div>
              <div className="font-bold text-ivory text-lg">HypothesisOS</div>
              <div className="text-xs text-slate">Decision Intelligence Platform</div>
            </div>
          </div>
          <div className="text-[10px] uppercase tracking-[0.15em] text-slate mb-2">Board Intelligence Brief</div>
          <h1 className="text-3xl font-black tracking-tight text-ivory">Decision Portfolio Overview</h1>
          <p className="mt-2 text-sm text-steel">Deterministic engine analysis · {date}</p>
        </div>
        <div className="mt-6 flex flex-wrap gap-6">
          <div>
            <div className="text-[10px] text-slate uppercase tracking-wide">Health Score</div>
            <div className={`data text-3xl font-black ${hb.cls}`}>{data.summary.healthScore}</div>
            <div className={`text-xs font-semibold ${hb.cls}`}>{hb.label}</div>
          </div>
          <div>
            <div className="text-[10px] text-slate uppercase tracking-wide">Total Decisions</div>
            <div className="data text-3xl font-black text-ivory">{data.summary.total}</div>
          </div>
          <div>
            <div className="text-[10px] text-slate uppercase tracking-wide">Critical Risks</div>
            <div className={`data text-3xl font-black ${data.summary.criticalRisks > 0 ? "text-kill" : "text-go"}`}>{data.summary.criticalRisks}</div>
          </div>
        </div>
      </div>

      {/* Portfolio Summary */}
      <div className="card mb-4">
        <div className="mb-4 flex items-baseline gap-3 border-b border-border-hair pb-3">
          <span className="data text-xs font-bold text-amber">§01</span>
          <h2 className="text-sm font-bold uppercase tracking-[0.1em] text-slate">Portfolio Summary</h2>
        </div>
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
          {[
            { label: "GO", value: String(data.summary.go), cls: "text-go" },
            { label: "UNRESOLVED", value: String(data.summary.unresolved), cls: "text-unresolved" },
            { label: "KILL", value: String(data.summary.kill), cls: "text-kill" },
            { label: "Avg Support", value: `${data.summary.avgSupport}%`, cls: "text-ivory" },
            { label: "Avg Debt", value: `${data.summary.avgDebt}%`, cls: data.summary.avgDebt > 50 ? "text-kill" : "text-ivory" },
            { label: "Reports", value: String(data.summary.totalReports), cls: "text-ivory" },
            { label: "Pending Approvals", value: String(data.summary.pendingApprovals), cls: "text-unresolved" },
          ].map((m) => (
            <div key={m.label} className="rounded-inner bg-white/3 px-3 py-3">
              <div className="text-[10px] uppercase tracking-wide text-slate">{m.label}</div>
              <div className={`data mt-1 text-xl font-bold ${m.cls}`}>{m.value}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Priority Actions */}
      {data.priorityActions.length > 0 && (
        <div className="card mb-4">
          <div className="mb-4 flex items-baseline gap-3 border-b border-border-hair pb-3">
            <span className="data text-xs font-bold text-amber">§02</span>
            <h2 className="text-sm font-bold uppercase tracking-[0.1em] text-slate">Priority Actions</h2>
          </div>
          <ol className="space-y-3">
            {data.priorityActions.map((a, i) => (
              <li key={i} className="flex items-start gap-3">
                <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-amber/15 text-xs font-bold text-amber">{i + 1}</span>
                <div>
                  <div className="flex items-center gap-2">
                    <span className="text-lg">{ACTION_TYPE_ICON[a.type] ?? "·"}</span>
                    <span className="text-[10px] uppercase tracking-wide text-slate">{a.type}</span>
                  </div>
                  <p className="text-sm text-steel">{a.action}</p>
                </div>
              </li>
            ))}
          </ol>
        </div>
      )}

      {/* Top Risks */}
      {data.topRisks.length > 0 && (
        <div className="card mb-4">
          <div className="mb-4 flex items-baseline gap-3 border-b border-border-hair pb-3">
            <span className="data text-xs font-bold text-amber">§03</span>
            <h2 className="text-sm font-bold uppercase tracking-[0.1em] text-slate">Top Risks</h2>
          </div>
          <div className="space-y-2">
            {data.topRisks.map((d, i) => (
              <div key={d.id} className="flex items-center gap-3 rounded-inner border border-border-hair px-3 py-2.5">
                <span className={`data text-sm font-bold ${RISK_CLS[d.risk ?? "MEDIUM"]}`}>#{i + 1}</span>
                <div className="min-w-0 flex-1">
                  <div className="text-sm text-ivory truncate">{d.title}</div>
                  <div className="text-[10px] text-slate">{d.verdict} · {(d.support * 100).toFixed(0)}% support · {d.daysOpen}d open</div>
                </div>
                <span className={`pill text-[10px] shrink-0 ${d.risk === "CRITICAL" || d.risk === "HIGH" ? "bg-kill/15 text-kill" : "bg-amber/15 text-unresolved"}`}>{d.risk}</span>
                <Link href={`/report/${d.id}`} className="btn-quiet text-xs py-1 shrink-0">Report</Link>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Near GO */}
      {data.nearGo.length > 0 && (
        <div className="card mb-4">
          <div className="mb-4 flex items-baseline gap-3 border-b border-border-hair pb-3">
            <span className="data text-xs font-bold text-amber">§04</span>
            <h2 className="text-sm font-bold uppercase tracking-[0.1em] text-slate">Near-GO Opportunities</h2>
          </div>
          <div className="space-y-2">
            {data.nearGo.map((d) => (
              <div key={d.id} className="flex items-center gap-3 rounded-inner bg-go/5 border border-go/20 px-3 py-2.5">
                <span className="text-go text-sm font-bold">◈</span>
                <div className="min-w-0 flex-1">
                  <div className="text-sm text-ivory truncate">{d.title}</div>
                  <div className="text-[10px] text-slate">{(d.support * 100).toFixed(0)}% support · {d.debt.toFixed(0)}% debt</div>
                </div>
                <Link href={`/report/${d.id}`} className="btn-ghost text-xs py-1 shrink-0">Review</Link>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Stalled */}
      {data.stalled.length > 0 && (
        <div className="card mb-4">
          <div className="mb-4 flex items-baseline gap-3 border-b border-border-hair pb-3">
            <span className="data text-xs font-bold text-amber">§05</span>
            <h2 className="text-sm font-bold uppercase tracking-[0.1em] text-slate">Stalled Decisions</h2>
          </div>
          <div className="space-y-2">
            {data.stalled.map((d) => (
              <div key={d.id} className="flex items-center gap-3 rounded-inner border border-border-hair px-3 py-2.5">
                <span className="text-slate text-sm">⏱</span>
                <div className="min-w-0 flex-1">
                  <div className="text-sm text-ivory truncate">{d.title}</div>
                  <div className="text-[10px] text-kill">{d.daysOpen} days without resolution</div>
                </div>
                <Link href={`/premortem/${d.id}`} className="btn-quiet text-xs py-1 shrink-0">Premortem</Link>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Footer */}
      <footer className="mt-6 border-t border-border-hair pt-5 text-center text-xs text-slate">
        <div className="flex items-center justify-center gap-2 mb-1">
          <Mark size={14} variant="mono" />
          <span className="font-semibold text-ivory">HypothesisOS</span>
          <span>·</span>
          <span>Decision Intelligence Platform</span>
        </div>
        <p>Deterministic engine analysis · {date}</p>
      </footer>
    </div>
  );
}
